services:

  mysql:
    image: mysql:8.0
    container_name: parameta-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parameta
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: parameta-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parameta?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SOAP_EMPLEADO_ADDRESS: http://localhost:8080/services/empleados
    depends_on:
      mysql:
        condition: service_healthy
