server:
  port: 8080

spring:
  application:
    name: empleados-service
  datasource:
    url: jdbc:mysql://localhost:3306/parameta?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

cxf:
  path: /services

soap:
  empleado:
    address: http://localhost:8080/services/empleados

logging:
  level:
    com.parameta: INFO
